2024/11/24 15:23:59 [error] 30#30: *1 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 10.0.2.2, server: , request: "GET /favicon.ico HTTP/1.1", host: "localhost:8801", referrer: "http://localhost:8801/"
2024/11/24 16:54:23 [error] 30#30: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.2.2, server: , request: "POST /app/user/api/v1/apuser/login_auth HTTP/1.1", upstream: "http://10.0.2.2:52601/user/api/v1/apuser/login_auth", host: "localhost:8801", referrer: "http://localhost:8801/login.html"
2024/11/24 16:54:35 [error] 30#30: *7 open() "/usr/share/nginx/html/js/axios.min.map" failed (2: No such file or directory), client: 10.0.2.2, server: , request: "GET /js/axios.min.map HTTP/1.1", host: "localhost:8801"
2024/11/24 16:54:45 [error] 30#30: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.2.2, server: , request: "POST /app/user/api/v1/apuser/login_auth HTTP/1.1", upstream: "http://10.0.2.2:52601/user/api/v1/apuser/login_auth", host: "localhost:8801", referrer: "http://localhost:8801/login.html"
2024/11/24 16:54:46 [error] 31#31: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.2.2, server: , request: "POST /app/user/api/v1/apuser/login_auth HTTP/1.1", upstream: "http://10.0.2.2:52601/user/api/v1/apuser/login_auth", host: "localhost:8801", referrer: "http://localhost:8801/login.html"
2024/11/24 16:54:46 [error] 30#30: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.2.2, server: , request: "POST /app/user/api/v1/apuser/login_auth HTTP/1.1", upstream: "http://10.0.2.2:52601/user/api/v1/apuser/login_auth", host: "localhost:8801", referrer: "http://localhost:8801/login.html"
2024/11/24 16:57:56 [error] 30#30: *14 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.2.2, server: , request: "POST /app/user/api/v1/apuser/login_auth HTTP/1.1", upstream: "http://10.0.2.2:52601/user/api/v1/apuser/login_auth", host: "localhost:8801", referrer: "http://localhost:8801/login.html"
2024/11/24 16:59:48 [error] 31#31: *18 open() "/usr/share/nginx/html/js/axios.min.map" failed (2: No such file or directory), client: 10.0.2.2, server: , request: "GET /js/axios.min.map HTTP/1.1", host: "localhost:8801"
2024/11/24 17:00:00 [error] 31#31: *18 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.2.2, server: , request: "POST /app/user/api/v1/apuser/login_auth HTTP/1.1", upstream: "http://10.0.2.2:52601/user/api/v1/apuser/login_auth", host: "localhost:8801", referrer: "http://localhost:8801/login.html"
2024/11/24 17:00:49 [error] 31#31: *18 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.2.2, server: , request: "POST /app/user/api/v1/apuser/login_auth HTTP/1.1", upstream: "http://10.0.2.2:52601/user/api/v1/apuser/login_auth", host: "localhost:8801", referrer: "http://localhost:8801/login.html"
2024/11/25 22:34:43 [error] 23#23: *1 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 10.0.2.2, server: , request: "GET /favicon.ico HTTP/1.1", host: "localhost:8801", referrer: "http://localhost:8801/"
2024/12/18 16:55:29 [error] 29#29: *1 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 10.0.2.2, server: , request: "GET /favicon.ico HTTP/1.1", host: "localhost:8801", referrer: "http://localhost:8801/"
2024/12/19 16:23:41 [error] 30#30: *1 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 10.0.2.2, server: , request: "GET /favicon.ico HTTP/1.1", host: "localhost:8801", referrer: "http://localhost:8801/"
2024/12/20 15:38:09 [error] 30#30: *5 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 10.0.2.2, server: , request: "GET /favicon.ico HTTP/1.1", host: "localhost:8801", referrer: "http://localhost:8801/"
2024/12/30 16:20:49 [error] 30#30: *1 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 10.0.2.2, server: , request: "GET /favicon.ico HTTP/1.1", host: "localhost:8801", referrer: "http://localhost:8801/"
2024/12/30 16:24:41 [error] 30#30: *5 open() "/usr/share/nginx/html/static/script/axios.min.map" failed (2: No such file or directory), client: 10.0.2.2, server: , request: "GET /static/script/axios.min.map HTTP/1.1", host: "localhost:8801"
2024/12/30 16:24:45 [error] 30#30: *5 open() "/usr/share/nginx/html/static/script/axios.min.map" failed (2: No such file or directory), client: 10.0.2.2, server: , request: "GET /static/script/axios.min.map HTTP/1.1", host: "localhost:8801"
2024/12/30 16:25:08 [error] 30#30: *5 open() "/usr/share/nginx/html/YT1/covert" failed (2: No such file or directory), client: 10.0.2.2, server: , request: "POST /YT1/covert HTTP/1.1", host: "localhost:8801", referrer: "http://localhost:8801/"
2024/12/30 16:28:02 [error] 30#30: *7 open() "/usr/share/nginx/html/static/script/axios.min.map" failed (2: No such file or directory), client: 10.0.2.2, server: , request: "GET /static/script/axios.min.map HTTP/1.1", host: "localhost:8801"
2024/12/30 16:28:58 [error] 30#30: *7 open() "/usr/share/nginx/html/static/script/axios.min.map" failed (2: No such file or directory), client: 10.0.2.2, server: , request: "GET /static/script/axios.min.map HTTP/1.1", host: "localhost:8801"
2024/12/30 16:36:01 [error] 30#30: *16 open() "/usr/share/nginx/html/static/script/axios.min.map" failed (2: No such file or directory), client: 10.0.2.2, server: , request: "GET /static/script/axios.min.map HTTP/1.1", host: "localhost:8801"
2024/12/31 12:19:28 [error] 30#30: *2 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 10.0.2.2, server: , request: "GET /favicon.ico HTTP/1.1", host: "localhost:8801", referrer: "http://localhost:8801/"
2024/12/31 12:19:31 [error] 30#30: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.2.2, server: , request: "POST /pc/YT1/api/v1/YT1/convert HTTP/1.1", upstream: "http://10.0.2.2:64101/YT1/api/v1/YT1/convert", host: "localhost:8801", referrer: "http://localhost:8801/"
2024/12/31 12:31:40 [error] 31#31: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.2.2, server: , request: "POST /pc/YT1/api/v1/YT1/convert HTTP/1.1", upstream: "http://10.0.2.2:64101/YT1/api/v1/YT1/convert", host: "localhost:8801", referrer: "http://localhost:8801/"
2024/12/31 12:31:40 [error] 31#31: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.2.2, server: , request: "POST /pc/YT1/api/v1/YT1/convert HTTP/1.1", upstream: "http://10.0.2.2:64101/YT1/api/v1/YT1/convert", host: "localhost:8801", referrer: "http://localhost:8801/"
2024/12/31 16:48:01 [error] 31#31: *78 open() "/usr/share/nginx/html/YT1/download" failed (2: No such file or directory), client: 10.0.2.2, server: , request: "GET /YT1/download?filename=Waves.mp3&t=1735634881992 HTTP/1.1", host: "localhost:8801", referrer: "http://localhost:8801/"
2024/12/31 16:50:15 [error] 31#31: *83 open() "/usr/share/nginx/html/YT1/download" failed (2: No such file or directory), client: 10.0.2.2, server: , request: "GET /YT1/download?filename=Waves.mp3&t=1735635015002 HTTP/1.1", host: "localhost:8801", referrer: "http://localhost:8801/"
